import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Header,
  TabStopType,
  TabStopPosition,
} from "docx";
import type { Project } from "@/types/models";
import { generateDocument } from "@/lib/claude";

const ESM_BLUE = "1F3864";

interface TrainingSection {
  role: string;
  product: string;
  getting_started: string[];
  key_workflows: string[];
  tips: string[];
}

interface TrainingGuideData {
  introduction: string;
  sections: TrainingSection[];
  support_contacts: string;
}

const TRAINING_SYSTEM = `You are a training content specialist for ESM Solutions, a procurement software company. Generate clear, step-by-step quick-start training content for customer staff who will use the ESM platform.

RULES:
- Write for non-technical users at higher education institutions
- Be specific to the products and configurations provided
- Steps should be actionable and concrete
- Do not fabricate feature names or UI paths that aren't in the data
- Where specifics are unknown, use "[Confirm with ESM team]"`;

function buildTrainingPrompt(projectData: Record<string, unknown>): string {
  return `Generate a Training Quick-Start Guide for the following ESM implementation. Return ONLY valid JSON.

PROJECT DATA:
${JSON.stringify(projectData, null, 2)}

Return JSON:
\`\`\`json
{
  "introduction": "1-2 paragraphs introducing the training guide",
  "sections": [
    {
      "role": "e.g., Requisitioner, Approver, Buyer",
      "product": "e.g., Purchase, Supplier Management",
      "getting_started": ["step 1", "step 2", ...],
      "key_workflows": ["workflow description 1", ...],
      "tips": ["tip 1", ...]
    }
  ],
  "support_contacts": "paragraph about getting help"
}
\`\`\``;
}

export async function generateTrainingGuide(project: Project): Promise<{ buffer: Buffer; fileName: string }> {
  const inputData = {
    customerName: project.customerName,
    products: project.products,
  };

  const guideData = await generateDocument<TrainingGuideData>(
    TRAINING_SYSTEM,
    buildTrainingPrompt(inputData),
  );

  const children: Paragraph[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [new TextRun({ text: "Training Quick-Start Guide", bold: true, size: 36, color: ESM_BLUE })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [new TextRun({ text: project.customerName, size: 26 })],
    }),
    new Paragraph({
      children: [new TextRun({ text: guideData.introduction, size: 22 })],
      spacing: { after: 200 },
    }),
  ];

  for (const section of guideData.sections) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: `${section.product} — ${section.role}`, bold: true, color: ESM_BLUE })],
      }),
    );

    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Getting Started", bold: true })],
      }),
    );
    for (let i = 0; i < section.getting_started.length; i++) {
      children.push(
        new Paragraph({
          numbering: { reference: "default-numbering", level: 0 },
          children: [new TextRun({ text: section.getting_started[i], size: 22 })],
        }),
      );
    }

    children.push(new Paragraph({ children: [] }));
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Key Workflows", bold: true })],
      }),
    );
    for (const wf of section.key_workflows) {
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun({ text: wf, size: 22 })],
        }),
      );
    }

    children.push(new Paragraph({ children: [] }));
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: "Tips", bold: true })],
      }),
    );
    for (const tip of section.tips) {
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun({ text: tip, size: 22, italics: true })],
        }),
      );
    }

    children.push(new Paragraph({ children: [] }));
  }

  children.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: "Getting Help", bold: true, color: ESM_BLUE })],
    }),
    new Paragraph({
      children: [new TextRun({ text: guideData.support_contacts, size: 22 })],
    }),
    new Paragraph({ children: [] }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "Generated by ESM Customer Hub — Requires management review before distribution",
          italics: true,
          size: 16,
          color: "999999",
        }),
      ],
    }),
  );

  const doc = new Document({
    numbering: {
      config: [
        {
          reference: "default-numbering",
          levels: [
            {
              level: 0,
              format: "decimal",
              text: "%1.",
              alignment: AlignmentType.START,
            },
          ],
        },
      ],
    },
    sections: [
      {
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                tabStops: [{ type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
                children: [new TextRun({ text: project.customerName, bold: true, color: ESM_BLUE, size: 18 })],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  const buffer = Buffer.from(await Packer.toBuffer(doc));
  const safeName = project.customerName.replace(/[^a-zA-Z0-9]/g, "_");
  return { buffer, fileName: `Training_QuickStart_${safeName}.docx` };
}
