export type ProjectStatus = "ON_TRACK" | "AT_RISK" | "OFF_TRACK";

export type DataSource = "CUSTOMER" | "SC" | "SMARTSHEET" | "WORKSHOP";

export type SectionKey =
  | "CUSTOMER_PROFILE"
  | "PHASE_SCOPE"
  | "SUCCESS_CRITERIA"
  | "PROJECT_TEAM"
  | "GOVERNANCE"
  | "COMMUNICATION"
  | "RESPONSIBILITIES"
  | "RISKS"
  | "INSTITUTIONAL_PROFILE"
  | "PROCUREMENT_GUIDELINES"
  | "APPROVAL_WORKFLOW"
  | "CATALOG_LANDSCAPE"
  | "GL_STRUCTURE"
  | "PO_PROCESS"
  | "RECEIVING_PROCESS"
  | "REPORTING_NEEDS"
  | "DATA_FILES_PLAN"
  | "TEST_PERMISSIONS"
  | "POWER_USERS"
  | "SSO_INFO"
  | "ESM_TESTING_ACCESS"
  | "TRANSACTION_PREFERENCES"
  | "SIGNOFF";

export const SECTION_KEYS: SectionKey[] = [
  "CUSTOMER_PROFILE",
  "PHASE_SCOPE",
  "SUCCESS_CRITERIA",
  "PROJECT_TEAM",
  "GOVERNANCE",
  "COMMUNICATION",
  "RESPONSIBILITIES",
  "RISKS",
  "INSTITUTIONAL_PROFILE",
  "PROCUREMENT_GUIDELINES",
  "APPROVAL_WORKFLOW",
  "CATALOG_LANDSCAPE",
  "GL_STRUCTURE",
  "PO_PROCESS",
  "RECEIVING_PROCESS",
  "REPORTING_NEEDS",
  "DATA_FILES_PLAN",
  "TEST_PERMISSIONS",
  "POWER_USERS",
  "SSO_INFO",
  "ESM_TESTING_ACCESS",
  "TRANSACTION_PREFERENCES",
  "SIGNOFF",
];

export type SectionStatus = "NOT_STARTED" | "IN_PROGRESS" | "IN_WORKSHOP" | "COMPLETE";

export type EsmRole = "SC" | "PM" | "SE" | "ADMIN";

export type ActorType = "CUSTOMER" | "ESM" | "SYSTEM";

export type AuditAction =
  | "PROJECT_CREATED"
  | "PORTAL_ACCESSED"
  | "SECTION_STARTED"
  | "SECTION_SAVED"
  | "SECTION_COMPLETED"
  | "SECTION_REOPENED"
  | "SECTION_MARKED_WORKSHOP"
  | "ATTACHMENT_UPLOADED"
  | "FORM_SUBMITTED"
  | "SMARTSHEET_WRITE_SUCCESS"
  | "SMARTSHEET_WRITE_FAILED"
  | "HUB_CREATED"
  | "CUSTOMER_CONTACT_ADDED"
  | "CONFLICT_CREATED"
  | "CONFLICT_RESOLVED"
  | "DOCUMENT_GENERATED"
  | "DOCUMENT_DOWNLOADED"
  | "NOTIFICATION_SENT"
  | "CONFIG_UPDATED";

export type DocumentStatus = "DRAFT" | "GENERATING" | "READY" | "ERROR";
